### ISSUE TITLE
Photo caption on same line as photo

### ISSUE THREAD

**Issue by mrpeterhanley** [mrpeterhanley/peterstestrepo#3]
Hi @GerardParsons the caption is on the same line as the photo

Could you please move it down to the next line?

**Comment by GerardParsons** [comment]
Hi @mrpeterhanley How do I get it on a new line?

**Comment by mrpeterhanley** [comment]
@GerardParsons it's markdown code not html, just enter a few times to put it on a new line

**Comment by GerardParsons** [comment]
Ok Thanks

**Comment by mrpeterhanley** [comment]
Thanks, it fixed the issue
